#!/bin/bash

# http://concourse.ci/implementing-resources.html#resource-check

set -e
set -x

# parse incoming config data
payload=`cat`
bucket=$(echo "$payload" | jq -r '.source.bucket')
path="$(echo "$payload" | jq -r '.source.path // ""')"

bucketFolder=$(echo "$payload" | jq -r '.params.bucketFolder // ""')

# export for `aws` cli
AWS_ACCESS_KEY_ID=$(echo "$payload" | jq -r '.source.access_key_id // empty')
AWS_SECRET_ACCESS_KEY=$(echo "$payload" | jq -r '.source.secret_access_key // empty')
AWS_DEFAULT_REGION=$(echo "$payload" | jq -r '.source.region // empty')

# Due to precedence rules, must be unset to support AWS IAM Roles.
if [ -n "$AWS_ACCESS_KEY_ID" ] && [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
  export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
fi

# Export AWS_DEFAULT_REGION if set
[ -n "$AWS_DEFAULT_REGION" ] && export AWS_DEFAULT_REGION

if [[ -n "$path" ]]; then
  prefix="$path/"
fi
if [[ -n "$bucketFolder" ]]; then
  prefix=${prefix}${bucketFolder}
fi

# Consider the most recent LastModified timestamp as the most recent version.
timestamps=$(aws s3api list-objects --bucket $bucket --prefix "$prefix" --query 'Contents[].{LastModified: LastModified}')
if [[ ! -z $timestamps ]]; then
recent="$(echo $timestamps | jq -r 'max_by(.LastModified)')"
fi

echo "[$recent]"
